version: '3.7'

services:
  minecraft:
    image: itzg/minecraft-server:java11
    container_name: minecraft
    environment:
      EULA: "TRUE"
      MEMORY: 4G
      TYPE: FORGE
      VERSION: 1.16.5
      FORGE_FORCE_REINSTALL: "false"
    volumes:
      - ./minecraft_data:/data
      - ./minecraft_data/mods:/data/mods
    ports:
      - "25565:25565"

volumes:
  minecraft_data:
  minecraft_mods: